on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }}
  TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and run Go program
      env:
        API_KEY: ${{ secrets.API_KEY }}
        TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}
      run: |
        go run main.go
